spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/dammemanga?sslMode=VERIFY_IDENTITY&useSSL=true&allowPublicKeyRetrieval=true&sessionVariables=sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'
spring.datasource.username=3c9AGg3Y2LBciMq.root
spring.datasource.password=LrJpcBZWLmOf96dy
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

jwt.secret=DamMeTruyenSecretKey12345678901234567890
jwt.expiration-ms=86400000

# Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect